Fix DB constraints
trpc/trpc pull request #1548
Opened 2022-02-21 08:18 UTC by FarazPatankar

This PR removes the uniqueness constraint from the `createdAt` and `updatedAt` properties as it wasn't really required and would cause issues when writing to the DB in bulk using `createMany`.

It also adds the `@updatedAt` flag on the `updatedAt` field so it updates properly on each update.

2022-02-21 08:56 UTC, KATT requested changes
Thanks for your contribution, @FarazPatankar ! I've added you as a contributor now. Could you please do the following for me? :point_down:

1. Accept the invitation - [link](https://github.com/trpc/trpc/invitations)
1. Push your branch to `origin` / `git@github.com:trpc/trpc.git`
1. Open a new PR instead of this
1. Close this PR
1. Add the actual migration that corresponds to this change

I really appreciate you spending time helping out with tRPC, feel free to continue to do so. All contributions are welcome, big or small!

2022-03-06 15:52 UTC, KATT commented
ping @FarazPatankar

2022-03-07 06:51 UTC, FarazPatankar commented
Oops, @KATT. I missed your comment the first time around and it looks like the invitation has now expired. Could you please resend it?

2022-03-07 12:23 UTC, FarazPatankar commented
Closing in favor of https://github.com/trpc/trpc/pull/1602

2022-03-07 12:23 UTC, closed without merging