docs: update introduction
trpc/trpc pull request #1555
Opened 2022-02-22 16:49 UTC by ahhshm

- renamed "Introducing tRPC​" into "Features". You already introduced tRPC in the first paragraph.
- synced the features section with README

2022-02-22 21:01 UTC, KATT requested changes
Please address the failing build 🙏 

If you setup github sponsors I'm going to send you a token of gratitude :)

2022-02-22 21:01 UTC, KATT commented on www/docs/main/introduction.md
> -<abbr title="TypeScript Remote Procedure Call">tRPC</abbr> allows you to easily build & consume fully typesafe APIs, without schemas or code generation.
I'd like to keep this

2022-02-23 04:35 UTC, ahhshm commented on www/docs/main/introduction.md
> -<abbr title="TypeScript Remote Procedure Call">tRPC</abbr> allows you to easily build & consume fully typesafe APIs, without schemas or code generation.
Done!

2022-02-23 05:01 UTC, ahhshm commented
Thank you so much. I really appreciate it but unfortunately, due to the US sanctions on Iran, my country's banks can't connect to the international bank system and I can't have a Paypal account so setting up github sponsors isn't possible for me.

2022-02-23 05:03 UTC, ahhshm commented on www/docs/main/introduction.md
> -<abbr title="TypeScript Remote Procedure Call">tRPC</abbr> allows you to easily build & consume fully typesafe APIs, without schemas or code generation.
Done

2022-02-23 09:06 UTC, KATT approved these changes

2022-02-23 09:06 UTC, merged