`typeof window !== 'undefined'` to test for client
trpc/trpc pull request #1728
Opened 2022-04-04 20:11 UTC by tianhuil

Since `process.browser` is deprecated, the recommended workaround for determining if we are on the client or server on nextjs is `typeof window !== 'undefined'`: 
https://github.com/zeit/next.js/issues/5354#issuecomment-520305040

2022-04-04 21:39 UTC, sachinraja approved these changes

2022-04-04 21:40 UTC, sachinraja commented
We have this a few other places in the examples and docs, so it'd be good if we can change those too

2022-04-05 14:34 UTC, KATT requested changes
Thanks for your contribution! :pray: :pray: 

I've added you as a contributor now, could you please do the following for me? :point_down:

1. Accept the invitation - [link](https://github.com/trpc/trpc/invitations)
1. Push your branch to `origin` / `git@github.com:trpc/trpc.git`
1. Open a new PR from origin instead
1. Close this PR


I really appreciate you spending time helping out with tRPC, feel free to continue to do so. All contributions are welcome, big or small!


Also, please make sure to find any other places in the codebase that uses `process.browser`.

2022-04-05 15:07 UTC, tianhuil commented
Closed in favor of https://github.com/trpc/trpc/pull/1730

2022-04-05 15:07 UTC, closed without merging