Update README.md
trpc/trpc pull request #2054
Opened 2022-06-30 08:11 UTC by KATT

2022-06-30 19:37 UTC, BassoliCodes submitted a review, later dismissed

2022-07-02 22:05 UTC, ixahmedxi approved these changes

2022-07-06 00:38 UTC, sachinraja requested changes

2022-07-06 00:38 UTC, sachinraja commented on README.md
> +> tRPC is rapdily gaining momentum!
```suggestion
> tRPC is rapidly gaining momentum!
```

2022-07-06 18:23 UTC, merged