feature: social icons
trpc/trpc pull request #2787
Opened 2022-09-22 23:07 UTC by tomheaton

Closes #2782

## 🎯 Changes

Added icons for GitHub, Twitter, and Discord social links

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

2022-09-24 10:55 UTC, tomheaton commented
Here is a preview of the icons.

<img width="139" alt="image" src="https://user-images.githubusercontent.com/50220137/192094048-4b808e29-2682-46bf-a81d-d17027acd50b.png">

<img width="138" alt="image" src="https://user-images.githubusercontent.com/50220137/192094054-e000d25b-f787-4802-a6b4-1585925e7811.png">

2022-09-24 11:02 UTC, juliusmarminge commented
> Here is a preview of the icons.
> 
> 
> 
> <img width="139" alt="image" src="https://user-images.githubusercontent.com/50220137/192094048-4b808e29-2682-46bf-a81d-d17027acd50b.png">
> 
> 
> 
> <img width="138" alt="image" src="https://user-images.githubusercontent.com/50220137/192094054-e000d25b-f787-4802-a6b4-1585925e7811.png">
> 
> 
> 
> 

Alignment looks a bit off for the discord one

2022-09-24 11:20 UTC, tomheaton commented
fixed
<img width="141" alt="image" src="https://user-images.githubusercontent.com/50220137/192095055-e9c1289e-8027-4729-a122-670d471730c3.png">

2022-09-24 12:49 UTC, ixahmedxi requested changes

2022-09-24 12:49 UTC, ixahmedxi commented on www/src/css/custom.css
> +  opacity: 0.6;
would add `@apply transition-colors opacity-60` here instead just because we have tailwind and transition hover is more pleasing.

2022-09-24 12:49 UTC, ixahmedxi commented on www/src/css/custom.css
> +  height: 24px;
change to tailwind `@apply`

2022-09-24 12:49 UTC, ixahmedxi commented on www/src/css/custom.css
> +  display: flex;
here as well.

2022-09-24 12:49 UTC, ixahmedxi commented on www/src/css/custom.css
> +  height: 24px;
and here.

2022-09-25 05:35 UTC, ixahmedxi approved these changes

2022-09-25 07:27 UTC, merged