docs: ✏️ SIWE Example Application
trpc/trpc pull request #3226
Opened 2022-11-22 18:07 UTC by codingwithmanny

Hi, I just wanted to contribute a repository that I made utilizing tRPC with Sign-In With Ethereum.

A Sign-In With Ethereum authentication web application with React and tRPC

BREAKING CHANGE: 🧨 N

Closes #

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

2022-11-22 18:48 UTC, KATT requested changes
- [ ] Please move it to the end :) 
- [ ] Add it to https://trpc.io/docs/awesome-trpc#-starting-points-example-projects-etc too!

2022-11-23 09:01 UTC, codingwithmanny commented
@KATT done :)

2022-11-23 21:10 UTC, KATT approved these changes

2022-11-25 09:53 UTC, KATT requested changes
Sorry, it has conflicts now!

2022-11-25 10:17 UTC, codingwithmanny commented
@KATT conflicts resolved. Just waiting on the tests to pass.

2022-11-25 20:13 UTC, codingwithmanny commented
😂  I swear I update this branch every hour to try and keep it up to date to get it to be merged.

2022-11-26 21:31 UTC, KATT approved these changes

2022-11-27 00:58 UTC, merged