docs: Initial API handler docs
trpc/trpc pull request #3341
Opened 2022-12-04 20:56 UTC by c-ehrlich

## 🎯 Changes

- Create initial API handler docs. Tried to keep it short and simple. I put it after the router and context docs as this makes the most sense to me.
- Link back to the API handler page from the context page

## ☑️ Todo

- Opening as a draft because linking to a sub-section of a page seems not to scroll to that section when the page is clicked. Maybe my syntax is incorrect? Will try to get this fixed, but interested in feedback on the actual docs in the meantime.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

2022-12-05 23:30 UTC, c-ehrlich commented
> > Opening as a draft because linking to a sub-section of a page seems not to scroll to that section when the page is clicked. Maybe my syntax is incorrect? Will try to get this fixed, but interested in feedback on the actual docs in the meantime.
> 
> Links seems to be working for me? You have an example of a broken one?
working for me as well now on the sample deployment, maybe issues related to my dev environment?

2022-12-05 23:37 UTC, juliusmarminge commented on www/docs/server/api-handler.md
> +tRPC is not a backend of its own, but rather lives inside of other backends such as Next.js or Express. Despite that, most of tRPC's features and syntax are the same no matter which backend you are u
... also called [adapter](https://trpc.io/docs/adapters)...

2022-12-05 23:37 UTC, juliusmarminge commented on www/docs/server/api-handler.md
> +The API Handler receives a request from the server, uses the `createContext` function to generate [Context](./context), and then sends the request and context to the [Router](./router).
context, procedure(?)

2022-12-05 23:38 UTC, juliusmarminge commented
Would also be nice to connect this https://trpc.io/docs/cors#enabling-on-the-server and explain that it can be wrappped etc

2022-12-11 19:02 UTC, KATT reviewed
Hey @c-ehrlich, could you have a look at julius' comments please? :)

2022-12-11 19:02 UTC, KATT commented on www/docs/server/context.md
> +The `createContext()` function is called for each request, and the result is propagated to all resolvers. You can use this to pass contextual data down to the resolvers.  This is done by including th
```suggestion
The `createContext()` function is called for each request, and the result is propagated to all resolvers. You can use this to pass contextual data down to the resolvers. This is done by including the context in the [API Handler](/docs/api-handler).
```

2022-12-11 22:19 UTC, c-ehrlich commented
> Would also be nice to connect this https://trpc.io/docs/cors#enabling-on-the-server and explain that it can be wrappped etc

Since Next.js is probably the most common way of using tRPC at this point, maybe it would be good to give an explicit example of this?

Something like: (but can maybe find a more "real" example)
```ts
const nextApiHandler = createNextApiHandler({
  router: appRouter,
  createContext,
});

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  // do anything that modifies the request or response
  // example: set a cookie
  res.setHeader(
    "set-cookie",
    "yourParameter=someValue; path=/; samesite=lax; httponly;"
  );
  return nextApiHandler(req, res);
}
```

What do you think?

2022-12-11 22:19 UTC, c-ehrlich commented on www/docs/server/api-handler.md
> +The API Handler receives a request from the server, uses the `createContext` function to generate [Context](./context), and then sends the request and context to the [Router](./router).
https://github.com/trpc/trpc/pull/3341/commits/d23b09e2e310e4fc6e8f498f0e8fd65518b4cd44

2022-12-11 22:20 UTC, c-ehrlich commented on www/docs/server/api-handler.md
> +tRPC is not a backend of its own, but rather lives inside of other backends such as Next.js or Express. Despite that, most of tRPC's features and syntax are the same no matter which backend you are u
https://github.com/trpc/trpc/pull/3341/commits/ac670db9e6cfebf6d401291b1c414ab07afc9dc9

2022-12-11 22:31 UTC, juliusmarminge commented
> (but can maybe find a more "real" example)

I think CORS is a valid example. I've used this in monorepos with Next.js as the backend and a 2nd Vite app for example:

![CleanShot 2022-12-11 at 23 28 41@2x](https://user-images.githubusercontent.com/51714798/206932681-8b45f83f-d6df-49f9-8ab4-97ecdda53fc8.png)

2022-12-26 22:27 UTC, c-ehrlich commented
Apologies for not touching this in two weeks, had a lot going on. Expanded on the API handler docs themselves, and also linked to them from the router and context pages as my experience from both tRPC and Theo discords is that many people struggle to understand the data flows.

2023-01-03 11:08 UTC, juliusmarminge requested changes

2023-01-03 11:08 UTC, juliusmarminge commented on www/docs/server/api-handler.md
> +The API Handler sits on a route in your server (usually `/api/trpc`, but this is just a convention) and processes all requests to that route and its subroutes. It receives a request from the server,
Links here are broken according to build error on Vercel

Should be https://trpc.io/docs/procedures

2023-01-03 11:10 UTC, juliusmarminge commented on www/docs/server/api-handler.md
> +The API Handler sits on a route in your server (usually `/api/trpc`, but this is just a convention) and processes all requests to that route and its subroutes. It receives a request from the server,
```suggestion
The API Handler sits on a route in your server (usually `/api/trpc`, but this is just a convention) and processes all requests to that route and its subroutes. It receives a request from the server, uses the `createContext` function to generate [context](./context), and then sends the request and context to a [procedure](./procedures) in the router.
```

2023-01-03 11:13 UTC, juliusmarminge approved these changes

2023-01-03 19:42 UTC, sachinraja approved these changes

2023-01-03 19:42 UTC, sachinraja commented on www/docs/server/api-handler.md
> +tRPC is not a backend of its own, but rather lives inside of other backends such as Next.js or Express. Despite that, most of tRPC's features and syntax are the same no matter which backend you are u
👏love this

2023-01-03 19:42 UTC, sachinraja commented on www/docs/server/api-handler.md
> +```
This is great!!

2023-01-03 19:49 UTC, merged