chore(www) show reading time ceil
trpc/trpc pull request #3519
Opened 2022-12-29 06:47 UTC by hrstmr

Closes #

## 🎯 Changes

Added Math.ceil() to pass the reading time to og Image generator as an int instead of a decimal, making is consistent with the visible reading time on the blog page

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

2022-12-29 06:55 UTC, hrstmr commented
Here is a screenshot of the og image showing `3.29 min read`
while the blog shows the read time as `4 min read`

![image](https://user-images.githubusercontent.com/37159938/209914867-f3504abd-b15b-4114-9893-9f820e649dcd.png)

![image](https://user-images.githubusercontent.com/37159938/209915098-04c89fa8-9434-4389-a6d9-fe59e290b463.png)

2023-01-01 19:47 UTC, KATT requested changes
Do it within the component instead please :)

2023-01-02 01:39 UTC, hrstmr commented
> Do it within the component instead please :)

Moved the Math.ceil logic to OG component as requested 😄

2023-01-02 17:23 UTC, KATT commented on www/og-image/pages/api/blog.tsx
> +              {Math.ceil(props.readingTimeInMinutes)} min read
```suggestion
              {Math.round(props.readingTimeInMinutes)} min read
```

2023-01-02 17:23 UTC, KATT approved these changes

2023-01-03 19:36 UTC, merged