docs: Added validator `runtypes` to docs
trpc/trpc pull request #4330
Opened 2023-05-07 22:22 UTC by AlexXanderGrib

## 🎯 Changes

- Added [`runtypes`](https://www.npmjs.com/package/runtypes) to supported validators list

It works without any changes to code, cause it has interface to `scale-ts`

```typescript
export type ParserScaleEsque<TInput> = {
  assert(value: unknown): asserts value is TInput;
};

// runtypes/src/runtype.ts
export interface RuntypeBase<A = unknown> {
  /**
   * Verifies that a value conforms to this runtype. When given a value that does
   * not conform to the runtype, throws an exception.
   */
  assert(x: any): asserts x is A;
}
```

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

2023-05-07 23:26 UTC, Nick-Lucas requested changes

2023-05-07 23:26 UTC, Nick-Lucas commented on www/docs/server/validators.md
> +```
Thank you for your contribution. We also have a paired tests file under ./packages/tests (apologies, away from PC so can't recall the exact file) which we like to add libraries to, this way we don't accidentally break compatibility in the future.

Could you please add it there too? I'll be happy to merge then 🙂

2023-05-08 09:29 UTC, Nick-Lucas approved these changes
LGTM, thank you for your contribution 🙂

2023-05-08 09:29 UTC, Nick-Lucas approved these changes

2023-05-08 09:47 UTC, Nick-Lucas commented
@AlexXanderGrib you have some linting failures. `pnpm lint-fix` `pnpm format-write` solve most of these issues :)

2023-05-08 18:08 UTC, AlexXanderGrib commented
@Nick-Lucas done. Lint passes

2023-05-08 20:22 UTC, juliusmarminge commented on www/docs/server/validators.md
> +export type AppRouter = typeof appRouter;
`t` & `t` :)

```suggestion
import { initTRPC } from '@trpc/server';
import * as T from 'runtypes';

const t = initTRPC.create();
const publicProcedure = t.procedure;

export const appRouter = t.router({
  hello: publicProcedure
    .input(T.Record({ name: T.String }))
    .output(T.Record({ greeting: T.String }))
    .query(({ input }) => {
      //      ^?
      return {
        greeting: `hello ${input.name}`,
      };
    }),
});

export type AppRouter = typeof appRouter;
```

You'll also need to add `runtypes` as a devDep to www for shiki to be able to compile.

I did it locally but couldn't push to your branch :/

2023-05-11 22:24 UTC, Nick-Lucas approved these changes

2023-05-11 23:31 UTC, juliusmarminge approved these changes

2023-05-11 23:31 UTC, merged