feat(server): stricter types for AnyRouter
trpc/trpc pull request #4531
Opened 2023-06-15 22:51 UTC by omermizr

Closes #4275

## 🎯 Changes

`AnyRouter` now uses `ProcedureRouterRecord` instead of `any` as `TRecord`.
The other changes are typing fixes required because of the change.

P.S - I'm not too familiar with the codebase, but I think this does what you want :)

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

2023-06-27 08:21 UTC, juliusmarminge requested changes

2023-06-27 20:30 UTC, omermizr commented on packages/react-query/src/createTRPCReact.tsx
> +  : TNo;
Yeah, they're in different packages and I wasn't sure how you guys do code sharing. What would you recommend?

2023-07-11 06:56 UTC, juliusmarminge commented on packages/react-query/src/createTRPCReact.tsx
> +  : TNo;
types can be shared from the server pacakge

2023-07-15 15:15 UTC, omermizr commented on packages/react-query/src/createTRPCReact.tsx
> +  : TNo;
Sure, but this type is super generic (it's a recipe similar to ts-toolbelt's `Equals`), and it doesn't make sense to make it public to `trpc`'s users. Where do you think I should put it?

2023-09-27 23:04 UTC, KATT requested changes
We won't be doing this right now. Happy for you to setup a PR against `next` though and do this

2023-09-27 23:04 UTC, closed without merging