docs: add missing zod import in code example
trpc/trpc pull request #4835
Opened 2023-09-26 08:00 UTC by AvaYnE2

## 🎯 Changes

add missing zod import in code example on the useInfiniteQuery page

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

2023-09-26 08:01 UTC, kamilogorek approved these changes

2023-09-27 22:42 UTC, KATT approved these changes

2023-09-28 00:31 UTC, KATT requested changes
Lint fail. Please run `pnpm format:write && git add . && git commit -m "lint fix" && git push`

2023-10-06 15:22 UTC, KATT approved these changes

2023-11-08 00:41 UTC, merged