feat(`server` + `client`): adapter and link for webworker
trpc/trpc pull request #4872
Opened 2023-10-02 22:35 UTC by Guria

## 🎯 Changes

This PR adds an adapter/link pair to run trpc server in a webworker.
It might be useful for example as temporary solution for migrating from SPA without nodejs backend.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made. 
- [ ] I have added or updated the tests related to the changes made.

Docs and tests after discussion :)

2023-10-06 15:21 UTC, KATT requested changes
We won't add more adapters at the moment - please make a separate PR where you expose the things you need to realise this

2023-10-17 14:40 UTC, Guria commented
@KATT updated

2023-10-18 08:16 UTC, kamilogorek commented
Change looks good to me, yet some ws tests are failing. Can you investigate?

2023-10-18 08:33 UTC, juliusmarminge commented on packages/server/src/rpc/parseTRPCMessage.ts
> +export function parseTRPCMessage(
Add a jsdoc comment thst this is public 

`/** @public */`

2023-10-20 15:32 UTC, Guria commented
updated: returned lost line and add public jsdoc

2023-10-20 18:43 UTC, juliusmarminge approved these changes

2023-10-26 08:20 UTC, Guria commented
@KATT  Anything else I need to do here, or just wait?

2023-10-26 08:26 UTC, KATT commented
Thanks for the nudge, I will look soon!

2023-10-26 09:20 UTC, KATT approved these changes

2023-10-26 09:33 UTC, merged