chore: upgrade prettier to v3
trpc/trpc pull request #5346
Opened 2024-01-16 21:12 UTC by ixahmedxi

2024-01-17 09:28 UTC, juliusmarminge submitted a review, later dismissed

2024-01-17 09:36 UTC, juliusmarminge commented
hmm typedoc isn't happy :/ 

![CleanShot 2024-01-17 at 10 36 25@2x](https://github.com/trpc/trpc/assets/51714798/64cd2bed-7e6b-4ed7-8b37-b93ff5023443)

2024-01-18 22:40 UTC, ixahmedxi commented
> hmm typedoc isn't happy :/
> 
> ![CleanShot 2024-01-17 at 10 36 25@2x](https://private-user-images.githubusercontent.com/51714798/297331954-64cd2bed-7e6b-4ed7-8b37-b93ff5023443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTc5MTQsIm5iZiI6MTcwNTYxNzYxNCwicGF0aCI6Ii81MTcxNDc5OC8yOTczMzE5NTQtNjRjZDJiZWQtN2U2Yi00ZWQ3LThiMzctYjkzZmY1MDIzNDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDIyNDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNmM1OGRiY2YxNzVkN2IyNTZjYTBlNDBiN2I4MzhhNjY1ODM2N2MyYmM1NTc5ODI4OTI4YWM3ZjE2ZWRmZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JZSYOJJ_RDXHmXScAvN58RJcVkaenS8-zNUT9gFuCDk)

I will investigate this

2024-01-19 01:51 UTC, KATT commented on www/package.json
> +    "prettier": "npm:prettier@^2.8.8",
I pinned this to prettier 2 -- @ixahmedxi see if we can just remove it here instead somehow. Idk how/why prettier is included in docusaurus' build

2024-01-19 14:19 UTC, KATT requested changes
Needs updating now that `@trpc/core` has been removed

Might be easiest to cherry-pick the `package.json`-changes to a new PR and let the autofixer do its thing

2024-09-06 13:19 UTC, closed without merging