Feat/websocket keep alive
trpc/trpc pull request #5715
Opened 2024-05-12 07:42 UTC by buraktt

Closes #2822

## 🎯 Changes

Heartbeat logic is implemented to keep connection alive.

## ✅ Checklist

- ✅  I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- ✅  If necessary, I have added documentation related to the changes made.
- ✅  I have added or updated the tests related to the changes made.

2024-05-12 09:19 UTC, KATT requested changes
Thanks for this!

Please use fake timers so the tests don't take over 3 seconds to run 🙏

2024-05-12 09:19 UTC, KATT commented on packages/tests/server/websockets.test.ts
> +      await waitMs(3500);
Please use [`useFakeTimers`](https://vitest.dev/guide/mocking.html#example) instead of real waiting so the test is snappy

2024-05-12 09:19 UTC, KATT commented on packages/server/src/adapters/ws.ts
> +  }, pingMs);
should we use [`unref`](https://nodejs.org/api/timers.html#immediateunref) here?
```suggestion
  }, pingMs).unref()
```

2024-05-12 11:53 UTC, buraktt commented
> Thanks for this!
> 
> Please use fake timers so the tests don't take over 3 seconds to run 🙏

Thanks for the quick review. Changes implemented 👍

2024-05-12 17:43 UTC, KATT approved these changes
Thanks!

FYI we'll have support for SSE soon too which will be nicer to use than WSS. you can peek in #5713

2024-05-12 17:43 UTC, KATT requested changes
Actually - one more thing - please add docs too! 🙏 Sorry I missed that was missing

2024-05-13 08:54 UTC, buraktt commented
@KATT docs updated.
SSE looks promising 🚀

2024-05-13 21:40 UTC, KATT approved these changes

2024-05-14 08:29 UTC, merged

2024-05-14 14:06 UTC, BeBoRE commented
Just for curiosity, when is this useful? Heartbeat is built into the WebSocket standard already.

2024-05-14 14:49 UTC, buraktt commented
@BeBoRE this is useful when you need to keep connection open by utilizing `ping`/`pong` control messages from `ws` package. (or drop them in a reasonable time to release the used resources)

2024-05-14 15:01 UTC, BeBoRE commented
Ohh, so heartbeat isn't done automatically? I thought the `ws` package would handle this automatically. My bad. Nice addition!