Upgrade and migrate Valibot integration to v0.31.0
trpc/trpc pull request #5770
Opened 2024-06-03 15:51 UTC by fabian-hiller

## 🎯 Changes

In Valibot v0.31.0 I will add a `parser` function to make it easier to use the schema library with tRPC. I have updated all Valibot related code, tests and documentation in this PR.

Our migration guide: https://valibot.dev/guides/migrate-to-v0.31.0/

> I am not sure if `next` is the right branch to merge into. Please let me know if you want me to update this PR.

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [x] If necessary, I have added documentation related to the changes made.
- [x] I have added or updated the tests related to the changes made.

2024-06-03 16:42 UTC, juliusmarminge approved these changes
Nice! When will 0.31 be released?

2024-06-03 17:13 UTC, fabian-hiller commented
Probably tomorrow or Wednesday.

2024-06-06 14:54 UTC, fabian-hiller commented
v0.31.0 is available: https://valibot.dev/blog/valibot-v0.31.0-is-finally-available/

2024-06-06 17:41 UTC, juliusmarminge requested changes

2024-06-06 17:41 UTC, juliusmarminge commented on packages/server/package.json
> +    "valibot": "0.31.0-rc.11",
Can you use the stable version please

2024-06-06 22:05 UTC, fabian-hiller commented on packages/server/package.json
> +    "valibot": "0.31.0-rc.11",
Done

2024-06-06 23:14 UTC, juliusmarminge approved these changes

2024-06-06 23:14 UTC, juliusmarminge commented on packages/tests/server/outputParser.test.ts
> +            ),
I love this new api

2024-06-06 23:22 UTC, merged