feat: support typeschema spec
trpc/trpc pull request #5909
Opened 2024-07-22 15:59 UTC by lobomfz

## 🎯 Changes

This is a barebones implementation of the [typeschema spec](https://typeschema.com/), it should allow any validation schema to be used without wrapping in a parser. This by itself, vastly improves the compatibility list, which adds @deepkit/type, @effect/schema, arktype, fastest-validator, io-ts and @sinclair/typebox to be used without the user wrapping the schema first.

Due to my unfamiliarity with trpc's codebase i'm sure this needs more effort and tests, so i'd like some guidance around what else should be done so this can be merged

Currently, typeschema has a bug with TS 5.5+ which breaks type inferrence. Due to this, most tests are failing, but applying patches from my [PR](https://github.com/decs/typeschema/pull/62) un-breaks them, so we should wait until that is merged.

To not introduce breaking changes, an additional try catch is added in ParseFn to try to wrap the input schema and extract its parse function

## ✅ Checklist

- [x] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

2024-09-06 13:13 UTC, KATT requested changes

2024-09-06 13:13 UTC, KATT commented on packages/server/src/unstable-core-do-not-import/parser.ts
> +export type Parser = ParserWithInputOutput<any, any> | ParserWithoutInput<any> | TypeschemaSchema
This should be in `ParserWithInputOutput` instead

2024-09-06 13:13 UTC, KATT commented on packages/server/src/unstable-core-do-not-import/parser.ts
> +      }
This shouldn't need to be changed

2024-09-06 13:17 UTC, KATT requested changes
Look at #5958 for a reference on how to do this

2024-10-05 08:01 UTC, Nick-Lucas commented
Hey @lobomfz  this has been idle for quite a long time so I'm going to close it out. The contribution would be very welcome though if you want to re-open

2024-10-05 08:01 UTC, closed without merging