fix: update fastify dependency
trpc/trpc pull request #6131
Opened 2024-10-17 16:21 UTC by jonapgar-groupby

Closes #

## 🎯 Changes

Update Fastify dependency to support passing Response object directly to Reply.send.
Earlier versions of fastify do not support passing a Response object directly. The capability was introduced here and is first available on version 4.26.0

https://github.com/fastify/fastify/commit/101ba57f894281421d902bf509adb4270473799d

Without this change, users who upgrade to v11 of tRPC who are using a prior version of fastify will receive an empty object `{}` for every response. No errors are emitted from the server, but tRPC clients will reject the response as invalid

 
## ✅ Checklist

- [ x ] I have followed the steps listed in the [Contributing guide](https://github.com/trpc/trpc/blob/main/CONTRIBUTING.md).
- [ ] If necessary, I have added documentation related to the changes made.
- [ ] I have added or updated the tests related to the changes made.

2024-10-17 22:08 UTC, KATT requested changes
Please update the test/support for the new fastify version

2024-10-18 17:18 UTC, jonapgar-groupby commented
Ah thanks I missed that 4.26.2 was coming from in the lockfile for examples/fastify-server. This caused the discrepancy with the referenced types. 

Should be all good now

2024-10-20 01:43 UTC, KATT reviewed
I don't have any problem updating this, but it doesn't matter / "do" anything afaict?

We just have fastify as a devDep so you can install whatever fastify version you want in your apps

2024-11-01 15:41 UTC, KATT commented
> Probably the best solution would be to declare fastify as a peer dep and mark it optional via[ peerDependenciesMeta](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependenciesmeta). The same could be done for `express` and several other dependencies currently declared as dev dependencies.

This would be great!

2024-12-29 21:06 UTC, closed without merging