Add support for async client headers
trpc/trpc pull request #902
Opened 2021-09-07 11:42 UTC by alaister

Hello,
This is a feature I need when working on a react native app using expo secure store, which has an async set/get interface.

At this stage this PR is more a proof of concept with the most simple of changes to get it working.

I am happy to change the implementation to suit your preferred style (for example maybe changing `getHeadersFn()` to always return a promise instead of handling it at the `httpRequest` level).
Also I am happy to add some tests/docs if you like this idea.

Cheers!

2021-09-07 11:44 UTC, KATT requested changes
Add tests otherwise 👍

2021-09-07 11:47 UTC, alaister commented
Are there any existing files for testing `httpRequest`? Or should I create a new one?
Also any specific types of tests you'd like?

2021-09-07 11:48 UTC, KATT reviewed
tiny tweaks here

also added you as a contributor, please make a branch based on origin so we can run tests, etc

https://github.com/trpc/trpc/invitations

2021-09-07 11:48 UTC, KATT commented on packages/client/src/internals/TRPCClient.ts
> +  headers?: HttpHeaders | (() => HttpHeaders) | (() => Promise<HttpHeaders>);
Tiny tweak:

```suggestion
  headers?: HttpHeaders | (() => HttpHeaders | Promise<HttpHeaders>)
```

2021-09-07 11:48 UTC, KATT commented on packages/client/src/links/core.ts
> +  headers: (() => HttpHeaders) | (() => Promise<HttpHeaders>);
```suggestion
  headers: (() => HttpHeaders | Promise<HttpHeaders>);
```

2021-09-07 14:27 UTC, KATT commented
> Are there any existing files for testing `httpRequest`? Or should I create a new one?
> Also any specific types of tests you'd like?

See https://github.com/trpc/trpc/pull/903

2021-09-08 12:43 UTC, KATT requested changes
This looks good but please push your branch to the trpc origin and open up a new PR from that instead of your fork

2021-09-08 12:53 UTC, merged

2021-09-08 12:55 UTC, alaister commented
Moved to #909