Fix procedure input type inference
trpc/trpc pull request #956
Opened 2021-09-16 16:33 UTC by mmkal

Fixes #949 

Could either supersede or be a follow-up to #955

This simplifies Procedure/ProcedureOptions down to one type each:

- `CreateProcedureWithInput`, `CreateProcedureWithoutInput`, `CreateProcedureOptions` -> `CreateProcedureOptions` (a single union type)
- `ProcedureWithInput`, `ProcedureWithoutInput`, `Procedure` -> `Procedure` (a single non-abstract class which _always_ has a `TInput`. The input just happens to be undefined if it was created without an input parser specified)

Note: there is one downside to this approach which is that for procedures with no inputs, the `input` prop passed to the resolver is typed as `unknown`, where ideally it'd be `undefined` or `never`. IMHO that's a pretty ok tradeoff given how much this simplifies both `procedure.ts` and `router.ts`.

2021-09-18 09:54 UTC, KATT requested changes
I really like the change but I don't wanna lose the `undefined` type inference - added extra safeguards for this in #963

2021-09-18 18:47 UTC, mmkal commented on packages/server/src/router.ts
> +  ) {
Note: for the implementation, the jsdoc and types are ignored so using `any` a bit more so using `any` and not duplicating the beta tag etc. here and in the equivalents for `query` and `mutation`.

2021-09-18 19:29 UTC, mmkal commented
@KATT updated, I brought back the overloads on `Router`, but removed the extensions of the `Procedure` class. So a smaller simplification, but it passes the new tests now. I also made procedure without input to have a `TInput` of `undefined | null` instead of `undefined`, since `undefined`-only would be a breaking change (one of the e2e tests caught this). Hopefully this change is ok - since the runtime check is `input != null`, it could be either at runtime so this seems appropriate to me. Up to you though if you think it needs another iteration though.

2021-09-20 16:21 UTC, KATT approved these changes
I moved the `undefined/null` logic into `inferProcedureInput` which feels more correct - let me know what you think @mmkal

2021-09-20 18:17 UTC, mmkal commented
LGTM!

2021-09-20 19:51 UTC, merged